### ISSUE TITLE
Annotate Notebooks

### ISSUE THREAD

**Issue by nuclearGoblin** [villano-lab/galactic-spin-W1#10]
Right now, some notebooks are clearly annotated and commented, but some are not. We should make sure each notebook thoroughly explains what it is doing and what the user needs to do to get it running.

**Comment by nuclearGoblin** [comment]
Annotation Progress, by notebook number:
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [X] 5
- [X] Bonus 1
- [X] Bonus 2
- [X] Widget 1
- [X] Widget 3
- [X] Widget 3

**Comment by nuclearGoblin** [comment]
@juditbergfalk @frankie-768 I believe we finished this with v1.0, is that true?

**Comment by juditbergfalk** [comment]
Hi Kitty, Yes, I believe so.  Judit Bergfalk From: Kitty HarrisSent: Tuesday, May 17, 2022 5:01 PMTo: villano-lab/galactic-spin-W1Cc: Judit Bergfalk; MentionSubject: Re: [villano-lab/galactic-spin-W1] Annotate Notebooks (Issue ***@***.*** @frankie-768 I believe we finished this with v1.0, is that true?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
